linters:
  disable-all: true
  enable:
    - goimports
    - revive
    - govet
    - errcheck
    - ineffassign
    - unconvert
    - misspell
    - prealloc
    - gosec

issues:
  exclude-use-default: false

linters-settings:
  govet:
    check-shadowing: true

  errcheck:
      ignore: "fmt:.*,Close"

  revive:
    # Use recommended configuration
    # @see https://github.com/mgechev/revive#recommended-configuration
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
#      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id


