version: '3'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_as_ci --default-authentication-plugin=mysql_native_password
    environment:
      TZ:  "/usr/share/zoneinfo/Asia/Tokyo" # wherever you want
      MYSQL_ROOT_PASSWORD: root

    ports:
      - '3306:3306'
volumes:
  mysql-data:
    driver: local
